"""Add planned_start and planned_end to Task

Revision ID: 01a8b8ca083c
Revises: 7063f7401218
Create Date: 2026-02-16 12:31:59.907268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a8b8ca083c'
down_revision: Union[str, Sequence[str], None] = '7063f7401218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'planned_end')
    op.drop_column('tasks', 'planned_start')
    # ### end Alembic commands ###
