"""Add deliverable fields

Revision ID: 06c36a9e3cb3
Revises: 3be7fdf88765
Create Date: 2026-02-16 18:53:16.580482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c36a9e3cb3'
down_revision: Union[str, Sequence[str], None] = '3be7fdf88765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_deliverable', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('discipline', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'discipline')
    op.drop_column('tasks', 'is_deliverable')
    # ### end Alembic commands ###
