"""Add is_summary and outline_level

Revision ID: 3be7fdf88765
Revises: ed213a820d77
Create Date: 2026-02-16 12:34:10.058065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be7fdf88765'
down_revision: Union[str, Sequence[str], None] = 'ed213a820d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_summary', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('outline_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'outline_level')
    op.drop_column('tasks', 'is_summary')
    # ### end Alembic commands ###
