"""Rename estimated_hours to original_duration and actual_hours to actual_cost

Revision ID: 7063f7401218
Revises: d10db9094acf
Create Date: 2026-02-16 12:14:08.472231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7063f7401218'
down_revision: Union[str, Sequence[str], None] = 'd10db9094acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
