"""Add P6 schema

Revision ID: 8f64d6110123
Revises: 
Create Date: 2026-02-16 11:43:37.916409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f64d6110123'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_id', sa.Integer(), nullable=False),
    sa.Column('successor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('lag', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['predecessor_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['successor_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_relationships_id'), 'task_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_task_relationships_project_id'), 'task_relationships', ['project_id'], unique=False)
    op.add_column('tasks', sa.Column('path', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('original_duration', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('remaining_duration', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('constraint_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('constraint_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('early_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('early_finish', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('late_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('late_finish', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('free_float', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('total_float', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('planned_value', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('earned_value', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('actual_cost', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('budget_at_completion', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('estimate_at_completion', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('resource_ids', sa.JSON(), nullable=True))
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tasks_path'), 'tasks', ['path'], unique=False)
    op.create_index(op.f('ix_tasks_wbs_code'), 'tasks', ['wbs_code'], unique=False)
    op.drop_column('tasks', 'dependencies')
    op.drop_column('tasks', 'notes')
    op.drop_column('tasks', 'responsible_party')
    op.drop_column('tasks', 'actual_hours')
    op.drop_column('tasks', 'planned_end')
    op.drop_column('tasks', 'is_summary')
    op.drop_column('tasks', 'outline_level')
    op.drop_column('tasks', 'estimated_hours')
    op.drop_column('tasks', 'helper_party')
    op.drop_column('tasks', 'planned_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('planned_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('helper_party', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('estimated_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('outline_level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('is_summary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('planned_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('actual_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('responsible_party', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('dependencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tasks_wbs_code'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_path'), table_name='tasks')
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tasks', 'resource_ids')
    op.drop_column('tasks', 'estimate_at_completion')
    op.drop_column('tasks', 'budget_at_completion')
    op.drop_column('tasks', 'actual_cost')
    op.drop_column('tasks', 'earned_value')
    op.drop_column('tasks', 'planned_value')
    op.drop_column('tasks', 'total_float')
    op.drop_column('tasks', 'free_float')
    op.drop_column('tasks', 'late_finish')
    op.drop_column('tasks', 'late_start')
    op.drop_column('tasks', 'early_finish')
    op.drop_column('tasks', 'early_start')
    op.drop_column('tasks', 'constraint_date')
    op.drop_column('tasks', 'constraint_type')
    op.drop_column('tasks', 'remaining_duration')
    op.drop_column('tasks', 'original_duration')
    op.drop_column('tasks', 'path')
    op.drop_index(op.f('ix_task_relationships_project_id'), table_name='task_relationships')
    op.drop_index(op.f('ix_task_relationships_id'), table_name='task_relationships')
    op.drop_table('task_relationships')
    # ### end Alembic commands ###
