"""Add responsible_party and fix logic

Revision ID: ed213a820d77
Revises: 01a8b8ca083c
Create Date: 2026-02-16 12:33:09.062336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed213a820d77'
down_revision: Union[str, Sequence[str], None] = '01a8b8ca083c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('responsible_party', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'responsible_party')
    # ### end Alembic commands ###
